/* -*- c -*- ------------------------------------------------------------- *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *   Copyright 2001-2025 H. Peter Anvin - All Rights Reserved
 *   Copyright (C) 2026 H. Peter Anvin <hpa@zytor.com>
 *
 * ----------------------------------------------------------------------- */

/*
 * config.h
 *
 * Sets up a common baseline environment, based on "autoconf" findings...
 */

#ifndef CONFIG_H
#define CONFIG_H 1

/* Feature enables for specific environments */
#ifdef __APPLE__
#if __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ >= 1070
#define __APPLE_USE_RFC_3542 1
#endif
#endif

/* Must be included before we include any system headers! */
#include "config/config.h"            /* autogenerated configuration header */

/* Standard includes */

#include <assert.h>
#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifdef HAVE_SYS_TYPES_H
#include <sys/types.h>
#endif

#ifdef HAVE_SYS_STAT_H
#include <sys/stat.h>
#endif

#ifdef HAVE_STRINGS_H
#include <strings.h>
#endif

#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif

#ifdef HAVE_SYS_TIME_H
#include <sys/time.h>
#endif

#ifdef HAVE_GRP_H
#include <grp.h>
#endif

#ifdef HAVE_FCNTL_H
#include <fcntl.h>
#endif

#if !defined(HAVE_POLL) && !defined(HAVE_PPOLL)
#undef HAVE_POLL_H
#endif

#ifdef HAVE_POLL_H
#include <poll.h>
#elif defined(HAVE_SYS_SELECT_H)
#include <sys/select.h>
#endif

#ifdef HAVE_SYS_IOCTL_H
#include <sys/ioctl.h>
#endif

#ifdef HAVE_SYS_SOCKET_H
#include <sys/socket.h>
#else
#ifdef HAVE_WINSOCK2_H
#include <winsock2.h>
#else
#ifdef HAVE_WINSOCK_H
#include <winsock.h>
#endif
#endif
#endif
#ifdef HAVE_NETDB_H
#include <netdb.h>
#endif

#ifdef HAVE_WCHAR_H
#include <wchar.h>
#endif
#ifdef HAVE_WCTYPE_H
#include <wctype.h>
#endif

#ifdef HAVE_LOCALE_H
#include <locale.h>
#endif

#ifdef HAVE_GETOPT_LONG
#include <getopt.h>
#else
#include "lib/getopt.h"
#endif

#ifdef HAVE_PATHS_H
#include <paths.h>
#endif

#ifndef _PATH_DEVNULL
#if defined(_WIN32) && !defined(__CYGWIN__)
#define _PATH_DEVNULL "\\\\.\\NUL"
#else
#define _PATH_DEVNULL "/dev/null"
#endif
#endif

/* Test for EAGAIN/EWOULDBLOCK */
#ifdef EAGAIN
#if defined(EWOULDBLOCK) && (EWOULDBLOCK != EAGAIN)
#define E_WOULD_BLOCK(x) ((x) == EAGAIN || (x) == EWOULDBLOCK)
#else
#define E_WOULD_BLOCK(x) ((x) == EAGAIN)
#endif
#else
#define E_WOULD_BLOCK(x) ((x) == EWOULDBLOCK)
#endif

/* Some broken systems care about text versus binary, but
   real Unix systems don't... */
#if !HAVE_DECL_O_TEXT
#define O_TEXT		0
#endif
#if !HAVE_DECL_O_BINARY
#define O_BINARY	0
#endif

#ifndef HAVE_DECL_O_NONBLOCK
# ifdef HAVE_DECL_O_NDELAY
#  define O_NONBLOCK	O_NDELAY
# else
#  define O_NONBLOCK	0
# endif
#endif

/* A lot of this is old BSD code.  Some newer systems don't approve. */

/* socklen_t */
#ifndef HAVE_SOCKLEN_T
typedef int socklen_t;
#endif

/* sa_family_t */
#ifndef HAVE_SA_FAMILY_T
/* This isn't safe to use in a structure; for that, need more smarts */
typedef unsigned int sa_family_t;
#endif

/* sysexits.h */

#ifdef HAVE_SYSEXITS_H
#include <sysexits.h>
#else
#define EX_USAGE        64      /* command line usage error */
#define EX_DATAERR      65      /* data format error */
#define EX_NOINPUT      66      /* cannot open input */
#define EX_NOUSER       67      /* addressee unknown */
#define EX_NOHOST       68      /* host name unknown */
#define EX_UNAVAILABLE  69      /* service unavailable */
#define EX_SOFTWARE     70      /* internal software error */
#define EX_OSERR        71      /* system error (e.g., can't fork) */
#define EX_OSFILE       72      /* critical OS file missing */
#define EX_CANTCREAT    73      /* can't create (user) output file */
#define EX_IOERR        74      /* input/output error */
#define EX_TEMPFAIL     75      /* temp failure; user is invited to retry */
#define EX_PROTOCOL     76      /* remote error in protocol */
#define EX_NOPERM       77      /* permission denied */
#define EX_CONFIG       78      /* configuration error */
#endif

/* If we don't have sigsetjmp() et all, setjmp() will have to do */

#ifndef HAVE_SIGSETJMP
#define sigsetjmp(x,y)  setjmp(x)
#define siglongjmp(x,y) longjmp(x,y)
#define sigjmp_buf jmp_buf
#endif

#ifndef HAVE_STPCPY
char *stpcpy(char *dst, const char *src); /* In lib/stpcpy.c */
#endif
#ifndef HAVE_MEMPCPY
static inline void *mempcpy(void *dst, const void *src, size_t n)
{
    return memcpy(dst, src, n) + n;
}
#endif

/* Various attributes */
#ifndef UNUSED
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
#endif

#ifndef likely
#ifdef __GNUC__
#define likely(x)   __builtin_expect(!!(x), 1)
#else
#define likely(x)   (!!(x))
#endif
#endif

#ifndef unlikely
#ifdef __GNUC__
#define unlikely(x) __builtin_expect(!!(x), 0)
#else
#define unlikely(x) (!!(x))
#endif
#endif

#ifndef PRINTF_FUNC
#ifdef __GNUC__
#define PRINTF_FUNC(fmt,lst) __attribute__((format(printf,fmt,lst)))
#else
#define PRINTF_FUNC(fmt,lst)
#endif
#endif

#ifndef CONST_FUNC
#ifdef __GNUC__
#define CONST_FUNC __attribute__((const))
#else
#define CONST_FUNC
#endif
#endif

#ifndef PURE_FUNC
#ifdef __GNUC__
#define PURE_FUNC __attribute__((pure))
#else
#define PURE_FUNC
#endif
#endif

/* For a malloc()-like function which never returns NULL */
#ifndef MALLOC_FUNC
#ifdef __GNUC__
#define MALLOC_FUNC(x) __attribute__((malloc,returns_nonnull,alloc_size(x)))
#else
#define MALLOC_FUNC(x)
#endif
#endif

/* For a calloc()-like function which never returns NULL */
#ifndef CALLOC_FUNC
#ifdef __GNUC__
#define CALLOC_FUNC(x,y) __attribute__((malloc,returns_nonnull,alloc_size(x,y)))
#else
#define CALLOC_FUNC(x,y)
#endif
#endif

/* For a realloc() function which never returns null */
#ifndef REALLOC_FUNC
#ifdef __GNUC__
#define REALLOC_FUNC(x) __attribute__((returns_nonnull,alloc_size(x)))
#else
#define REALLOC_FUNC(x)
#endif
#endif

/* A function which returns a pointer to a newly allocated buffer, never NULL */
#ifndef NEWBUF_FUNC
#ifdef __GNUC__
#define NEWBUF_FUNC __attribute__((malloc,returns_nonnull))
#else
#define NEWBUF_FUNC
#endif
#endif

/* Inhibit inlining */
#ifndef NOINLINE_FUNC
#ifdef __GNUC__
#define NOINLINE_FUNC __attribute__((noinline))
#else
#define NOINLINE_FUNC
#endif
#endif

/* The max and min values of an integer type (assumes 2's complement) */
#define IS_SIGNED(t)	 ((t)(-1) < (t)0)
#define TYPE_MKMASK(t,x) ((t)(x) + ((t)(x) - 1))
#define TYPE_MAX(t)	 TYPE_MKMASK(t, (t)1 << (sizeof(t)*CHAR_BIT-1-IS_SIGNED(t)))
#define TYPE_MIN(t)	 ((t)~TYPE_MAX(t))

/* off_t and OFF_T_MAX */
#ifndef HAVE_OFF_T
typedef long off_t;
#endif
#ifndef OFF_T_MAX
#define OFF_T_MAX TYPE_MAX(off_t)
#endif

/* netinet/in.h, and possible missing pieces */
#include <netinet/in.h>

/* arpa/inet.h, and possible missing pieces */
#ifdef HAVE_ARPA_INET_H
#include <arpa/inet.h>
#endif

#include "common/tftp.h"

/* Prototypes for libxtra functions */

#ifndef HAVE_DAEMON
int daemon(int, int);
#endif

#ifndef HAVE_GETADDRINFO
#ifndef HAVE_STRUCT_ADDRINFO_AI_ADDR
struct addrinfo {
    int     ai_flags;
    int     ai_family;
    int     ai_socktype;
    int     ai_protocol;
    size_t  ai_addrlen;
    struct sockaddr *ai_addr;
    char    *ai_canonname;
    struct addrinfo *ai_next;
};
#endif
int getaddrinfo(const char *, const char *, const struct addrinfo *,
                struct addrinfo **);
void freeaddrinfo(struct addrinfo *);
const char *gai_strerror(int);


#ifndef EAI_NONAME
#define EAI_NONAME      -2    /* NAME or SERVICE is unknown.  */
#endif
#ifndef EAI_ADDRFAMILY
#define EAI_ADDRFAMILY -9    /* Address family for NAME not supported.  */
#endif
#ifndef EAI_MEMORY
#define EAI_MEMORY      -10   /* Memory allocation failure.  */
#endif
#ifndef EAI_SYSTEM
#define EAI_SYSTEM      -11   /* System error returned in `errno'.  */
#endif
#endif

#ifndef AI_CANONNAME
#define AI_CANONNAME    0
#endif

#ifndef AI_ADDRCONFIG
#define AI_ADDRCONFIG   0
#endif

#ifndef INET6_ADDRSTRLEN
#define INET6_ADDRSTRLEN 46
#endif

#ifndef HAVE_INET_NTOP
const char *inet_ntop(int, const void *, char *, socklen_t);
#endif

/* If unlocked stdio is unavailable, use normal stdio */
#ifndef HAVE_FREAD_UNLOCKED
# define fread_unlocked(p,s,n,f) fread(p,s,n,f)
#endif
#ifndef HAVE_FWRITE_UNLOCKED
# define fwrite_unlocked(p,s,n,f) fwrite(p,s,n,f)
#endif
#ifndef HAVE_GETC_UNLOCKED
# define getc_unlocked(f) getc(f)
#endif
#ifndef HAVE_PUTC_UNLOCKED
# define putc_unlocked(c,f) putc(c,f)
#endif
#ifndef HAVE_FERROR_UNLOCKED
# define ferror_unlocked(f) ferror(f)
#endif
#ifndef HAVE_FEOF_UNLOCKED
# define feof_unlocked(f) feof(f)
#endif
#ifndef HAVE_FILENO_UNLOCKED
# define fileno_unlocked(f) fileno(f)
#endif
#ifndef HAVE_FFLUSH_UNLOCKED
# define fflush_unlocked(f) fflush(f)
#endif

/* strnlen(): an unoptimized version is small enough to inline */
#ifndef HAVE_STRNLEN
static inline size_t strnlen(const char *str, size_t n)
{
    size_t len = 0;
    while (len < n) {
        if (!str[len])
            break;
        len++;
    }
    return len;
}
#endif

/* HAVE_IPV6 as a boolean */
#ifdef HAVE_IPV6
# define WITH_IPV6 1
#else
# define WITH_IPV6 0
#endif

/* Handy macros */

#define ARRAY_SIZE(x)  (sizeof(x)/sizeof(x[0]))
#define ARRAY_END(x)   (&(x)[ARRAY_SIZE(x)])
#define ARRAY_FOREACH(var,array) \
    for ((var) = (array); (var) < ARRAY_END(array); (var)++)
#define MIN(x,y) ((x) < (y) ? (x) : (y))
#define MAX(x,y) ((x) > (y) ? (x) : (y))

#endif
